Github verification
btcpayserver/btcpayserver-plugin-builder pull request #43
Opened 2024-11-15 12:52 UTC by TChukwuleta

Resolves #31

2024-11-18 04:33 UTC, rockstardev commented on PluginBuilder/Views/Account/GithubAccountVerification.cshtml
> +        </div>
```suggestion
        <div class="alert alert-info">
        To verify your GitHub account, <a href="https://gist.github.com/" target="_blank" style="color: inherit; text-decoration: underline;">create a public gist</a> with the following content:<br>
        <span id="token" class="fs-3">ca9b473b-5e3a-480d-886e-0cb7136e81d3</span><br><br>
        The gist description and filename do not matter, just ensure the provided token is entered as the content.<br>
        Once the public gist is created, copy its full URL and click the "Verify" button to complete verification.
        </div>
```

Proposed improved text

2024-11-18 04:34 UTC, rockstardev requested changes
We need the GitHub verification flow to mirror the Email verification flow as demonstrated here:

[[VIDEO URL]](https://github.com/user-attachments/assets/ed9f3e31-2407-43e8-8f1b-112361f669b1)

The main difference will be that the `Verify` button for GitHub will redirect users to the new page you have built. After successful verification, it should redirect back to the Account Details page, displaying a `Confirmed` label next to GitHub.

---

**Changes Needed for Verifying GitHub Account:**

Here's the current setup:

![image](https://github.com/user-attachments/assets/b45e6374-ead9-4f19-b92e-1142b3aad1f6)

1. Combine the Github Profile Url and Public Gist Id into a single textbox - Public Gist Url. From this URL, we will extract the GitHub username.
2. The form needs better formatting—make the width similar to the Account Details form.
3. The instructions should be clearer. I will provide a proposed commit with the revised text.

---

**Database Changes for GitHub Verification:**

When saving GitHub verification in the database, instead of a simple boolean, save the full public URL of the Gist. This allows us to periodically check if the Gist still exists—if the user deletes the Gist, we will revoke verification.

---

**Remove Separate Trigger for GitHub Account Verification:**

Finally, eliminate the separate blocker/trigger for GitHub account verification during the build. The trigger will now be in the Account Details, so there’s no need for this check to be added here. For now, we want users to continue being able to publish new versions without verifying, and we can implement these checks later.

2024-11-18 04:35 UTC, rockstardev commented
Also in future please avoid adding multiple reviewers to prevent unnecessary work. For this repository, request a review from me... and once we reach the appropriate milestones, we can present it to the rest of the team together.

2024-11-18 15:24 UTC, TChukwuleta commented
@rockstardev  flow has been updated

2024-11-25 05:05 UTC, rockstardev approved these changes
LGTM and thanks!

2024-11-25 05:05 UTC, merged