Include VerifiedEmailForPluginPublish feature flag
btcpayserver/btcpayserver-plugin-builder pull request #45
Opened 2024-11-20 13:32 UTC by TChukwuleta

Resolves #41 

Include VerifiedEmailForPluginPublish feature flag to prevent unverified plugin publish

2024-11-29 14:35 UTC, rockstardev requested changes
As we spoke through DMs, this should be done through Settings table rather than `launchSettings.json` so we avoid server restarts.

https://github.com/btcpayserver/btcpayserver-plugin-builder/blob/master/PluginBuilder/Data/Scripts/11.SettingsTable.sql

2024-12-05 05:18 UTC, TChukwuleta commented
updated the flow to follow Settings table

2025-03-20 23:04 UTC, rockstardev approved these changes
ACK

2025-03-20 23:04 UTC, rockstardev commented
Great work on this @TChukwuleta

2025-03-20 23:05 UTC, merged